function Home() {
    return <h1>VOCÊ É UM MULHERÃO INCRIVEL, UMA GATA, CHEIROSA, GOSTOSA, A COSIA MAIS LINDA DESSE UNIVERSO E EU AMO AMAR VOCÊ PS.: ODIEI NÃO TE VER HOJE, NÃO FAREI MAIS ISSO, NÃO TA COMPENSANDO</h1>
}

export default Home;